routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['register' => false, 'logout' => false]);

Route::get('/', 'HomeController@index')->name('home');

Route::get('lang/{locale}', 'LocalizationController@index')->name('lang');

// Route::get('pusher', function(){
// 	$user = \Auth::user();
// 	// $email = new CreateUserMail($user);
// 	// \Mail::to('carlosanselmi2@gmail.com')->send(new App\Mail\CreateUserMail($user));
// 	\Mail::to('carlosanselmi2@gmail.com')->send(new CreateUserMail(\Auth::user()));
// 	// new \App\Mail\CreateUserMail(\Auth::user());
// 	// event(new App\Events\CreateUserEvent());
//     // event(new App\Events\TestEvent('Broadcasting in Laravel using Pusher!'));

// 	return view('pusher');
// })->name('home');
// 

Route::middleware('auth')->group(function() {

	/* Profile */
	Route::namespace('Auth')->group(function() {

		Route::middleware('role:super-admin|client-admin')->group(function() {
			Route::resource('users', 'ProfileController');
		});

		Route::prefix('profile')->name('profile.')->group(function() {

			Route::get('/', 'ProfileController@profile')->name('index');

			Route::post('/update/{id}', 'ProfileController@updateProfile')->name('update');

			Route::post('/updateAuthUserPassword', 'ProfileController@updateAuthUserPassword')->name('update.password');
		});
	});

	Route::middleware('role:super-admin')->namespace('CRUD')->group(function(){
		Route::resource('permissions', 'PermissionsController')->except(['show']);
		// Route::resource('conexiones_empresas', 'ConexionesEmpresasController')->except(['show']);
		Route::resource('empresas', 'EmpresasController')->except(['show']);
		Route::resource('conexiones', 'ConexionesController')->except(['show']);
		Route::resource('dispositivos', 'DispositivoController')->except(['show']);
		Route::resource('precio_estabilizado', 'PrecioEstabilizadoController')->except(['show']);
		Route::resource('barras', 'BarrasController')->except(['show']);
		Route::resource('barras_empresas', 'BarraEmpresaController')->except(['show']);
		Route::resource('modalidad_calculo_empresas', 'ModalidadCalculoEmpresasController')->except(['show']);
		Route::resource('periodos_cen', 'PeriodoCenController')->except(['show']);
	});	

});	

Route::get('/recursos', function () {
	return view('layouts.recursos');
});

Route::get('ajaxlogin','Auth\LoginController@ajaxLogin')->name('is_users');

Route::get('model1','Modules\AssetManagement\EnergiaMedidoresController@getMaxAndMinTBL');

Route::prefix('ppagos')->name('ppagos.')->namespace('PPagoCen')->group(function() {
	Route::get('/','PpController@index')->name('index'); // Descarga el .csv
	Route::get('/empresas','PpController@empresas')->name('empresas'); // Aquí sube todo el .json de empresas que se encuentra en el /public/test
	Route::get('/bancos','PpController@bancos')->name('bancos');// Aquí sube todo el .json de bancos que se encuentra en el /public/test
	Route::get('/empresas/get', 'PpController@getEmpresas')->name('getEmpresas');
	Route::get('/bancos/get', 'PpController@getBancos')->name('getEmpresas');
	Route::get('/bancos/export/{option?}', 'PpController@export')->name('export');
	Route::get('/process', 'PpController@process')->name('process');
});


Route::get('/403', function() {
	return view('errors.403');
})->name('errors.403');

Route::get('/503', function() {
	return view('errors.503');
})->name('errors.503');

app/Models/AssetManagement/CMG.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class CMG extends Model
{
	
  protected $table = 'cmg';
  
  protected $fillable = [
    'id',
    'id_empresa',
    'id_user',
    'id_tipo_doc_cen',
    'hora',
    'dia',
    'barra',
    'cmg_mills_kwh',
    'usd',
    'cmg_usd_kwh',
    'periodo',
    'created_at',
    'updated_at'
  ];

  /**
   * Retorna la tabla del modelos
   * @return String tabla
   */
	static function getTableModel()
	{
		return (new static)->getTable();
	}
}

app/Models/AssetManagement/ComentariosEmpresa.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;
use IzyTech\Validator\Contracts\ValidatorInterface;

class ComentariosEmpresa extends Model
{
	
  protected $tabla = 'comentarios_empresas';
  
  public $timestamps = false;

  protected $fillable = [
		'id_empresa',
		'id_comentario'
  ];

  protected $datatable = [
    'id_empresa',
    'id_comentario'
  ];
  
  protected $rules = [
    ValidatorInterface::RULE_CREATE => [
      'id_empresa' => 'required',
      'id_comentario' => 'required'
    ],

    ValidatorInterface::RULE_UPDATE => [
      'id_empresa' => 'required',
      'id_comentario' => 'required'
    ] 
  ];

  /**
  * Get the validation rules that apply to the request.
  *
  * @return array
  */
  public function rules()
  {
    return $this->rules;
  }
  /**
   * Retorna la tabla del modelos
   * @return String tabla
   */
	static function getTableModel()
	{
		return (new static)->getTable();
	}

  public function empresa ()
  {
    return $this->hasOne('App\Models\AssetManagement\Empresa', 'id', 'id_empresa');
  }

  public function comentario ()
  {
    return $this->belongsTo('App\Models\AssetManagement\ModulosComentario', 'id_comentario', 'id');
  }
}

app/Models/AssetManagement/Correspondencia.php
<?php

namespace App\Models\AssetManagement;

use App\Models\AssetManagement\ModelMensajeria;

class Correspondencia extends ModelMensajeria
{
  
}

app/Models/AssetManagement/Empresa.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use App\Models\Conexion as conexion;
use App\Models\Dispositivo as dispositivo;
use IzyTech\Validator\Contracts\ValidatorInterface;

class Empresa extends Model
{
    use HasSlug;

    protected $fillable = [
        'id',
        'rut',
        'slug',
        'nombre_xls',
        'label',
        'order',
        'potencia_instalada',
        'coordenadas_lat',
        'coordenadas_lng',
        'url_gmaps',
        'fecha_inicio'
        // 'razon_social',
        // 'giro',
        // 'acteco',
        // 'cdgsiisucur',
        // 'direccion',
        // 'comuna',
        // 'ciudad'
    ];

    protected $datatable = [
        'rut',
        'nombre_xls',
        'label',
        'order',
        'potencia_instalada',
        'coordenadas_lat',
        'coordenadas_lng',
        'url_gmaps',
        'fecha_inicio'
    ];

    protected $rules = [
        ValidatorInterface::RULE_CREATE => [
            'rut' => 'required',
            'nombre_xls' => 'min:3|unique:empresas',
            'order' => 'required',
            'fecha_inicio' => 'required'
        ],

        ValidatorInterface::RULE_UPDATE => [
            'rut' => 'required',
            'nombre_xls' => 'min:3|unique:empresas, nombre_xls,id,:id',
            'order' => 'required',
            'fecha_inicio' => 'required'
        ]
    ];

    /**
    * Get the validation rules that apply to the request.
    *
    * @return array
    */
    public function rules()
    {
        return $this->rules;
    }

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('nombre_xls')
            ->saveSlugsTo('slug');
    }

    public function __construct(array $empresa = [])
    {
        parent::__construct($empresa);

        static::retrieved(function ($empresa) {
            $empresa->conexion;
            $empresa->dispositivo;
        });
    }

    public function users ()
    {
        return $this->belongsToMany('App\User','empresas_users', 'empresa_id', 'user_id')
                    ->withTimestamps();
    }

}

app/Models/AssetManagement/EmpresaIntegracion.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class EmpresaIntegracion extends Model
{
	
  protected $table = "empresa_integracion";

  protected $fillable = [
  	'empresa_id',
  	'tipo_integracion_id',
  	'deleted_at'
  ];
}

app/Models/AssetManagement/EmpresasPadres.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class EmpresasPadres extends Model
{
	
  protected $table = 'empresas_padres';
  
  protected $fillable = [
    'id',
  	'nombre',
  	'logo'
  ];

  /**
   * Retorna la tabla del modelos
   * @return String tabla
   */
	static function getTableModel()
	{
		return (new static)->getTable();
	}
}

app/Models/AssetManagement/EmpresasRelacion.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class EmpresasRelacion extends Model
{
	
  protected $table = 'empresas_relacion';
  
  protected $fillable = [
  	'id_empresa_padre',
  	'id_empresa_hija'
  ];

  /**
   * Retorna la tabla del modelos
   * @return String tabla
   */
	static function getTableModel()
	{
		return (new static)->getTable();
	}
}

app/Models/AssetManagement/Energia.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class Energia extends Model
{
	
  protected $table = 'balance_economico_energia_cen';
  
  protected $fillable = [
  	'id_empresa_deudora',
  	'id_empresa_acreedora',
  	'id_tipo_doc_cen',
  	'costo',
  	'periodo'
  ];

  /**
   * Retorna la tabla del modelos
   * @return String tabla
   */
	static function getTableModel()
	{
		return (new static)->getTable();
	}
}

app/Models/AssetManagement/EnergiaMedidoresCEN.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class EnergiaMedidoresCEN extends Model
{
	
  protected $table = 'energia_medidores_cen';

  protected $fillable = [
		'id_empresa',
		'id_user',
		'id_tipo_doc_cen',
		'periodo',
		'dia',
		'hora',
		'kwh_in',
		'kwh_out'
  ];
}

app/Models/AssetManagement/EnergiaMedidoresOE.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class EnergiaMedidoresOE extends Model
{
	
  protected $table = 'energia_medidores_oe';

  protected $fillable = [
		'id_empresa',
		'id_user',
		'periodo',
		'hora',
		'kwh_in',
		'kwh_out'
  ];
}

app/Models/AssetManagement/EnergiaMedidoresOEoriginal.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class EnergiaMedidoresOEoriginal extends Model
{
	
  protected $table = 'energia_medidores_oe_original';

	protected $fillable = [
		'id_empresa',
		'id_user',
		'periodo',
		'hora',
		'kwh_in',
		'kwh_out'
	];
}

app/Models/AssetManagement/EnergiaMedidoresPFV.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class EnergiaMedidoresPFV extends Model
{
	
  protected $table = 'energia_medidores_pfv';

  protected $fillable = [
		'id',
		'id_empresa',
		'id_user',
		'periodo',
		'kwh_in',
		'kwh_out',
		'medidor_date',
		'created_at',
		'updated_at'
  ];
}

app/Models/AssetManagement/Facturas.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class Facturas extends Model
{
	
  protected $table = 'facturas';
  
  protected $fillable = [
    'id',
    'periodo',
    'id_empresa_deudora',
    'id_empresa_acreedora',
    'id_modulo',
    'id_tipo_dte',
    'folio',
    'fecha_emision',
    'fecha_aceptacion',
    'fecha_aceptacion_ts',
    'fecha_vencimiento',
    'forma_pago',
    'monto_neto',
    'monto_bruto',
    'iva',
    'pago_codigo',
    'pago_fecha',
    'created_at',
    'updated_at'
  ];

  /**
   * Retorna la tabla del modelos
   * @return String tabla
   */
	static function getTableModel()
	{
		return (new static)->getTable();
  }
  
  public function empresas() 
  {
      return $this->belongsToMany('App\Models\AssetManagement\Empresa');
  }

  public function getPagoAttribute()
  {
    return $this->pago_fecha;
  }

  /**
   * Get columns.
   *
   * @return array
   */
  static function getColumns()
  {
    return [
      ['title' => 'id', 'data' => 'id'],
      ['title' => 'periodo', 'data' => 'periodo'],
      ['title' => 'deudora', 'data' => 'id_empresa_deudora'],
      ['title' => 'acreedora', 'data' => 'id_empresa_acreedora'],
      ['title' => 'tipo_dte', 'data' => 'id_tipo_dte'],
      ['title' => 'aceptacion', 'data' => 'fecha_aceptacion'],
      ['title' => 'aceptacion_ts', 'data' => 'fecha_aceptacion_ts'],
      ['title' => 'fecha_vencimiento', 'data' => 'fecha_vencimiento'],
      ['title' => 'forma_pago', 'data' => 'forma_pago'],
      ['title' => 'monto_neto', 'data' => 'monto_neto'],
      ['title' => 'monto_bruto', 'data' => 'monto_bruto'],
      ['title' => 'iva','data' => 'iva'],
      ['title' => 'pago_fecha', 'data' => 'pago_fecha'],
      ['title' => 'created_at', 'data' => 'created_at'],
      ['title' => 'updated_at', 'data' => 'updated_at']
    ];
  }
}

app/Models/AssetManagement/FacturasRecibidas.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;

class FacturasRecibidas extends Model
{
	
  protected $table = 'facturas_recibidas';
  
  protected $fillable = [
    'id',
    'periodo',
    'id_empresa',
    'id_empresa_deudora',
    'id_empresa_acreedora',
    'id_tipo_dte',
    'folio',
    'fecha_emision',
    'fecha_aceptacion',
    'fecha_aceptacion_ts',
    'fecha_vencimiento',
    'forma_pago',
    'monto_neto',
    'monto_bruto',
    'iva',
    'created_at',
    'updated_at'
  ];

  /**
   * Retorna la tabla del modelos
   * @return String tabla
   */
	static function getTableModel()
	{
		return (new static)->getTable();
	}
}

app/Models/AssetManagement/Incidencia.php
<?php

namespace App\Models\AssetManagement;

use App\Models\AssetManagement\ModelMensajeria;

class Incidencia extends ModelMensajeria
{
}

app/Models/AssetManagement/Informe.php
<?php

namespace App\Models\AssetManagement;

use App\Models\AssetManagement\ModelMensajeria;

class Informe extends ModelMensajeria
{
}

app/Models/AssetManagement/InformesOM.php
<?php

namespace App\Models\AssetManagement;

use App\Models\AssetManagement\ModelMensajeria;

class InformesOM extends ModelMensajeria
{
  protected $table = 'om_informes';
}

app/Models/AssetManagement/ModulosComentario.php
<?php

namespace App\Models\AssetManagement;

use Illuminate\Database\Eloquent\Model;
use IzyTech\Validator\Contracts\ValidatorInterface;
use App\Models\AssetManagement\ComentariosEmpresa;

class ModulosComentario extends Model
{
	
  protected $fillable = [
    'modulo',
    'id_user',
    'id_modulo',
		'comentario'
  ];

  protected $datatable = [
    'modulo',
    'id_user',
    'id_modulo',
		'comentario'
  ];
  
  /**
   * Retorna la tabla del modelos
   * @return String tabla
   */
	static function getTableModel()
	{
		return (new static)->getTable();
	}

  public function user()
  {
    return $this->hasOne('App\User', 'id', 'id_user');
  }

  public function correspondencia () 
  {
    return $this->hasOne('App\Models\AssetManagement\Correspondencia', 'id', 'id_modulo');
  }

  public function informe () 
  {
    return $this->hasOne('App\Models\AssetManagement\Informe', 'id', 'id_modulo');
  }

  public function informeOM () 
  {
    return $this->hasOne('App\Models\AssetManagement\InformesOM', 'id', 'id_modulo');
  }

  public function incidencia () 
  {
    return $this->hasOne('App\Models\AssetManagement\Incidencia', 'id', 'id_modulo');
  }

  public function empresas ()
  {
    return $this->hasMany(ComentariosEmpresa::class, 'id_comentario', 'id');
  }

  public function getEmpresasParent ()
  {
    switch ($this->modulo) {
      case 'correspondencias':
        return $this->correspondencia->empresas;
      break;
      case 'informes':
        return $this->informe->empresas;
      break;
      case 'incidencias':
        return $this->incidencia->empresas;
      break;
      case 'informeOM':
        return $this->informeOM->empresas;
      break;  
      default:
        return [];
        break;
    }
  }

  public function getEmpresasIdsAttribute()
  {
    $empresas = [];
    foreach ($this->empresas as $key =>  $e) {
      array_push($empresas, $e->empresa->id);
    }
    return $empresas;
  }
}

resources/views/modules/asset-management/facturacion/emitidas.blade.php
@extends('layouts.app')

@content
    @slot('breadcrumbItems')
        <li class="breadcrumb-item active text-uppercase" aria-current="page">{{__('app.facturacion.emitidas')}}</li>
    @endslot
    @slot('title')
        <h1 class="display-6 text-uppercase">{{__('app.facturacion.emitidas')}}</h1>
    @endslot
    <form id="formFilter" class="form-validator">
      <div class="form-row mb-3">
        @php
            $selecEmpresa = Auth::user()->empresas->first();
            $selecEmpresa = $selecEmpresa ? $selecEmpresa->id : null
        @endphp

        @SelectCompanys(['class'=>"col-6 col-sm-6 col-companys",'selected' => Input::get('empresa_xls') ? Input::get('empresa_xls') : $selecEmpresa])

        @SelectMonths(['class'=>"col-6 col-sm-6 col-months", "selected" => isset($month) ? $month :  null ])

        @SelectYears(['class'=>"col-6 col-sm-6 col-years", "selected" => isset($year) ? $year : null ])

        @include('layouts.components.selects.modules',['type' => 'select', 'modules' => [
                  [
                    'label' => __('app.Todos'),
                    'value' => 0,
                  ],
                  [
                    'label' => __('app.Energía'),
                    'value' => 1,
                  ],
                  [
                    'label' => __('app.Potencia'),
                    'value' => 2,
                  ]
                ],
        'class'=>"col-6 col-md-3 col-lg-2"])

        <div class="col-12 col-md-4 col-lg-4 col-xl-2">
          <div class="form-group">
            <label class="d-none d-sm-inline-block w-100"></label>
            <div class="btn-group w-100" role="group" aria-label="Button group with nested dropdown">
              <button type="button" class="btn btn--padding btn-primary-hover" id="filtrar">
                <i class="fa fa-search" aria-hidden="true"></i> {{__('app.filtrar')}}
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>

    <div class="form-row">
    <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4" style="padding-bottom: 25px;">
      <div class="list bg-success shadow-sm rounded overflow-hidden">
        <div class="list-item">
          <div class="list-thumb bg-success-active rounded-circle shadow-sm p-2 h3 mx-auto mb-0" style="color: #FFFFFF;">
            <i class="fa fa-hand-holding-usd"></i>
          </div>
          <div class="list-body text-right"  style='font-family: "Courier New"'>
            <span class="list-title text-white" style='font-weight: bold;'>$ {{ number_format($data['total'],0,',','.') }}</span>
            <span class="list-content text-white">
            Total Facturas de emitidas
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-12 table-responsive">
          <table class="table table-hover table-sm">
            <thead>
              <tr>
                <th class="h6 font-weight-bold">{{__('app.Fecha de recepción SII') }}</th>
                <th class="h6 font-weight-bold">{{__('validation.attributes.rut') }}</th>
                <th class="h6 font-weight-bold">{{__('validation.attributes.razon_social') }}</th>
                <th class="h6 font-weight-bold">{{__('validation.attributes.tipo') }}</th>
                <th class="h6 font-weight-bold">{{__('validation.attributes.folio') }}</th>
                <th class="h6 font-weight-bold">{{__('validation.attributes.fecha_emision')}}</th>
                <th class="h6 font-weight-bold">{{__('validation.attributes.periodo_cen')}}</th>
                <th class="h6 font-weight-bold">{{__('validation.attributes.monto_total')}}</th>
                <th class="h6 font-weight-bold">{{__('validation.attributes.pago_recibido')}}</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($data['collects'] as $key => $row)
                <tr class="">
                  <td scope="row">{{$row->fecha_aceptacion_ts}}</td>
                  <td scope="row">{{strtoupper(AppHelpers::rut($row->id_empresa_deudora))}}</td>
                  <td scope="row">{{strtoupper(AppHelpers::razon_social($row->id_empresa_deudora))}}</td>
                  <td scope="row">{{AppHelpers::tipo_factura($row->id_tipo_dte)}}</td>
                  <td scope="row">{{$row->folio}}</td>
                  <td scope="row">{{ date('d/m/Y', strtotime($row->fecha_emision)) }}</td>
                  <td scope="row">{{$row->periodo}}</td>
                  <td scope="row">$ {{ number_format($row->monto_bruto,0,',','.') }}</td>
                  <td scope="row" class="align-center">
                    <h3 class="align-center" style="opacity: .8">
                      <span class="badge badge-{{   $row->pago ? 'primary' : 'danger' }} font-weight-normal w-100">
                        {{  $row->pago ? __('app.si') : __('app.no') }}
                      </span>
                    </h3>
                  </td>
                </tr>
              @empty
                <tr>
                  <td colspan="9">
                    <div class="alert alert-light text-dark font-weight-bold rounded text-center py3" role="alert">
                      {{__('app.SIN REGISTROS OBTENIDOS')}}
                    </div>
                  </td>
                </tr>
              @endforelse
            </tbody>
          </table>
        </div>
        <div class="col-12 text-center max-auto">
          {{ $data['collects']->links() }}
        </div>
      </div>
    </div>
@endcontent

@section('scripts')
  @parent
  <script src="{{ asset('plugins/js-form-validator-2.1/js-form-validator.js') }}"></script>
  <script>
    let formData = serialize(document.querySelector('#formFilter'));
    Array.prototype.forEach.call(document.getElementsByClassName("page-link"), function(element, index) {
      element.setAttribute("href", element.getAttribute("href") + '&' + formData);
    });

    document.getElementById("filtrar").addEventListener("click", function() {
      if(document.querySelector('.form-validator')) {
        document.body.classList.add("loading");
        window.location = window.location.pathname + '?' + $('form.form-validator').serialize();
      }
    });
  </script>
@endsection